version: 0.0
os: linux
files:
  - source: /
    destination: /home/apiuat-seaverse-backend
    file_exists_behavior: OVERWRITE
permissions:
  
  - object: /home/apiuat-seaverse-backend/scripts
    pattern: "*.sh"
    mode: "755"
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/stop_container.sh
      runas: root
      timeout: 300
  AfterInstall:
    - location: scripts/build_container.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_container.sh
      runas: root
      timeout: 300