

services:
  # Redis Service
  # redis:
  #   image: redis
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - app-network

  # Enrollment Worker 
  enrollment-worker:
    build:
      context: .
      dockerfile: Dockerfile.enrollmentworker
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

  # CSV Worker
  csv-worker:
    build:
      context: .
      dockerfile: Dockerfile.csvworker
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge