const { ObjectId } = require("../../../tools");
const { AuthUser, Role, CustomError, ErrorName, CurrentDateTime } = require("../../../util");

const { TrainingCertificate } = require("./training_certificate_model");
const { Subscriber } = require("../../saas/subscriber/subscriber_model");
const { User } = require("../../user/user_model");
const { Employee } = require("../../user/employee/employee_model");

const CounterHelper = require("../../counters/counter_helper");
const NotificationHelper = require("../../notifications/notification_helper");

const NotificationType = require("../../notifications/notification_type.json");

module.exports = {
    // createOrUpdateTrainingCertificate: async ({ input, session }, context) => {
    //     const { userId, subscriberId } = AuthUser(context);
    //
    //     const filterConditions = {
    //         _id: input._id ?? ObjectId(),
    //         subscriber: subscriberId,
    //         trainingRegistration: input.trainingRegistration,
    //     };
    //
    //     const updateData = {};
    //
    //     if (input.organizationName) updateData.organizationName = input.organizationName;
    //     if (input.trainingTitle) updateData.trainingTitle = input.trainingTitle;
    //     if (input.trainingDescription) updateData.trainingDescription = input.trainingDescription;
    //     if (input.status) updateData.status = input.status;
    //     if (input.gradeMark) updateData.organizationName.gradeMark = input.gradeMark;
    //     if (input.trainerName) updateData.trainerName = input.trainerName;
    //     if (input.badge) updateData.badge = input.badge;
    //     if (input.certificateNumber) updateData.certificateNumber = input.certificateNumber;
    //     if (input.completedAt) updateData.completedAt = input.completedAt;
    //     if (input.generatedAt) updateData.generatedAt = input.generatedAt;
    //     if (input.expiresAt) updateData.expiresAt = input.expiresAt;
    //
    //     const savedCertificate = await TrainingCertificate.findOneAndUpdate(
    //         filterConditions,
    //         {
    //             ...filterConditions,
    //             ...updateData,
    //         },
    //         {
    //             upsert: true,
    //             new: true,
    //             setDefaultsOnInsert: true,
    //             runValidators: true,
    //             lean: true,
    //             session,
    //         }
    //     );
    //
    //     if (!savedCertificate) throw CustomError(ErrorName.FAILED);
    //     return savedCertificate;
    // },
    generateTrainingCertificateNumber: async ({ subscriberId, session }) => {
        // const existingSubscriber = await Subscriber.findById(subscriberId)
        //     .lean()
        //     .select("user name")
        //     .populate({ path: "user", select: "firstName" });
        //
        // if (!existingSubscriber) throw CustomError(ErrorName.FAILED);

        const currentYear = CurrentDateTime().utcDateTimeObj.year();

        const savedCounter = await CounterHelper.updateCounter({
            subscriberId,
            modelName: TrainingCertificate.modelName,
            // filterConditions: { year: currentYear },
            session,
        });

        if (!savedCounter) throw CustomError(ErrorName.FAILED);
        //5M-2022-121313
        // const subscriberName = existingSubscriber.user?.firstName ?? "";
        const subscriberName = process.env.SUBSCRIBER;
        return `${subscriberName.slice(0, 2).toUpperCase()}-${currentYear}-${savedCounter.count
            .toString()
            .padStart(6, "0")}`;
    },
    // sendCertificateGenerationNotification: async ({ notificationData }) => {
    //     try {
    //         const createdUser = await User.findById(notificationData.createdBy).select("firstName");
    //         const employeeDetails = await Employee.findById(notificationData.employee)
    //             .populate({
    //                 path: "user",
    //                 select: "firstName",
    //             })
    //             .select("user");
    //
    //         const notification = {
    //             subscriberId: notificationData.subscriber,
    //             title: [
    //                 {
    //                     lang: "en",
    //                     value: "Generated Training Certificate",
    //                 },
    //             ],
    //             message: [
    //                 {
    //                     lang: "en",
    //                     value: `Employee ${employeeDetails.user.firstName} certificate generated by ${createdUser.firstName}}`,
    //                 },
    //             ],
    //             notificationType: NotificationType.CERTIFICATE_GENERATED,
    //             notifyAdmin: true,
    //             notifiers: [notificationData.trainer],
    //             employeeNotifiers: [notificationData.employee],
    //             affected: [
    //                 {
    //                     targetRef: "TrainingCertificate",
    //                     target: notificationData.affected,
    //                 },
    //             ],
    //             // additionalInfo
    //         };
    //
    //         await NotificationHelper.createNotification(notification);
    //     } catch (e) {
    //         console.log(
    //             "training_helper.sendCertificateGenerationNotification:exception:",
    //             e?.message
    //         );
    //     }
    // },
};
