
module.exports = {
    TITLE_REQUIRED: "Please provide a title for the learning plan.",
    LEARNING_PLAN_NOT_FOUND: "Learning Plan not Found",
    TARGET_AUDIENCE_REQUIRED: "Please select a target audience for the learning plan.",
    AUDIENCE_SELECTION_REQUIRED: "Audience selection is mandatory. Please choose an option.",
    SELECT_COURSES_REQUIRED: "You must select at least one course.",
    INVALID_CONDITION_FOR_ALL_EMPLOYEES: "Condition type is not applicable when audience selection is set to 'All Employees'.",
    CONDITION_TYPE_REQUIRED_FOR_AUTOMATIC: "Condition type is required when audience selection is 'Automatic'.",
    INVALID_GROUP_IDS_FOR_TARGET_AUDIENCE: "Group IDs are not allowed when the target audience is set to 'Everyone in the Organization'.",
    CONDITIONAL_FIELDS_NOT_ALLOWED_FOR_ALL_EMPLOYEES: "Conditional custom fields are not allowed for 'All Employees' audience selection.",
    AUTOMATIC_SELECTION_FIELDS_REQUIRED: "Condition type and conditional custom fields are required for 'Automatic' audience selection.",
    INVALID_CONDITIONAL_FIELDS_FOR_MANUAL: "Condition type and conditional custom fields are not applicable for 'Manual' audience selection.",
    USER_OBJECT_IDS_REQUIRED_FOR_MANUAL: "Please add at least one learner for 'Manual' audience selection.",
    INVALID_USER_OBJECT_IDS: "One or more learners provided are invalid. Please check the selection.",
    INVALID_CONDITIONAL_CUSTOM_FIELDS: "The conditional custom fields provided are invalid.",
    INVALID_COURSE_SELECTION: "Please select a valid course from the available options.",
    LEARNING_PLAN_EXISTS: "A learning plan with this title already exists. Please choose a different title.",
    GROUP_IDS_REQUIRED_FOR_GROUP_BASED: "Group IDs are required for a group-based target audience.",
    INVALID_GROUP_IDS: "One or more group IDs provided are invalid. Please verify the group selection.",
    INVALID_GROUP_TYPE: "The group type provided is invalid. Please check the configuration.",
    INVALID_ROLE_ID: "The role provided is invalid. Please check your selection.",
    INVALID_REG_STATUS: "Registration status must be either true or false.",
    INVALID_VESSEL_STATUS: "Vessel status must be one of the following: 'Assigned', 'Onboarded', or 'Onshore'.",
    GROUP_IDS_GROUP_TYPE_REQUIRED_FOR_GROUP_BASED: "Both group IDs and group type are required for a group-based field.",
    VALUE_OF_FIELD_NOT_REQUIRED_FOR_GROUP_BASED: "Field value is not required for group-based fields.",
    INVALID_CONDITIONAL_FIELDS_FOR_GROUP_BASED: "The conditional custom fields provided for a group-based audience selection are invalid.",
    IS_RETIRED_COURSES_SELECTION: "One or more courses selected have been moved to the retired state. To continue editing the learning plan, please remove the retired courses."
};